version: "3.9"

services:
  nats:
    image: nats:latest
    ports:
        - "4222:4222"
        - "8222:8222"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "webdir123R"
        ACCEPT_EULA: "Y"
    depends_on:
        - nats
  orderservice:
    image: arslanahmad656/nats-sql-orderservice:0.4
    ports:
        - "9100:5000"
    depends_on:
        - nats
        - sqlserver
  billingservice:
    image: arslanahmad656/nats-sql-billingservice:0.4
    ports:
        - "9101:5000"
    depends_on:
        - nats
        - sqlserver
        - orderservice
    